# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev42+gd2e5cc5.d20230215'
__version_tuple__ = version_tuple = (0, 1, 'dev42', 'gd2e5cc5.d20230215')
