# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev37+g851c3db.d20230214'
__version_tuple__ = version_tuple = (0, 1, 'dev37', 'g851c3db.d20230214')
