# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev8+gd5245f2.d20230207'
__version_tuple__ = version_tuple = (0, 1, 'dev8', 'gd5245f2.d20230207')
