# file generated by setuptools_scm
# don't change, don't track in version control
<<<<<<< HEAD
__version__ = version = '0.1.dev8+gd5245f2.d20230207'
__version_tuple__ = version_tuple = (0, 1, 'dev8', 'gd5245f2.d20230207')
=======
__version__ = version = "1.0.1.dev0+gb5540f7.d20230204"
__version_tuple__ = version_tuple = (1, 0, 1, "dev0", "gb5540f7.d20230204")
>>>>>>> d5245f28ea16f66e7147fba2dec779ebe227cc5b
